server:
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

spring:
  profiles:
    active: prod

  datasource:
    username: scc
    url: jdbc:postgresql://scc-rds.ch28o2ai2p5m.ap-northeast-2.rds.amazonaws.com:5432/scc
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 25000
      data-source-properties.cachePrepStmts: true
      data-source-properties.prepStmtCacheSize: 250
      data-source-properties.prepStmtCacheSqlLimit: 2048
      pool-name: writer
      maximum-pool-size: 32
      minimum-idle: 10

  jpa:
    open-in-view: false

# logging:
#   config: /app/conf/logback.xml

# actuator settings
management:
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
        add-additional-paths: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    web:
      server:
        auto-time-requests: true
        max-uri-tags: 1024

sentry:
  logging:
    enabled: true
  environment: prod

scc:
  environment: prod
  s3:
    imageUpload:
      bucketName: scc-prod-accessibility-images
      thumbnailBucketName: scc-prod-accessibility-thumbnails
      bannerBucketName: scc-prod-home-banners
  cloudfront:
    domain: d1whorck6z6h62.cloudfront.net
  slack:
    channel:
      reportAccessibility: "#scc-accessibility-report"
