apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scc-server.fullname" . }}
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
data:
  application.yaml: |-
{{ printf "%s/application.yaml" .Values.filesDir | .Files.Get | indent 4 }}
