apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-update-challenge-ranking
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/updateChallengeRanks"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-create-closed-place-candidates
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  # At 11:00 pm (KST) every day
  schedule: "0 14 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/createClosedPlaceCandidates"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-update-external-refresh-tokens
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  # At 10:00 pm (KST) every day
  schedule: "0 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/updateExternalRefreshTokens"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-batch-postprocess-images
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  # In 23:00 ~ 05:00 for every 10 minutes (KST) every day
  schedule: "*/10 14-20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/batchProcessUnprocessedAccessibilityImages"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-migrate-images
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  # 2/30
  schedule: "0 0 30 2 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/migrateOldImagesToNewImages"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-send-scheduled-push-notifications
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  # every 10 minutes
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/sendScheduledPushNotifications"
          restartPolicy: OnFailure
