apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-blur-face-in-accessibility-images
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/blurFacesInLatestPlaceAccessibilityImages"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-update-ranking
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: appropriate/curl
            args: 
            - "--fail"
            - "-XPOST"
            - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/updateAccessibilityRanks"
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: scc-update-challenge-ranking
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: appropriate/curl
              args:
                - "--fail"
                - "-XPOST"
                - "http://scc-server.{{ .Release.Namespace }}.svc.cluster.local/updateChallengeRanks"
          restartPolicy: OnFailure
