apiVersion: batch/v1
kind: Job
metadata:
  # 마지막의 randAlphaNum은 argocd sync 시 무조건 새 job을 생성시키기 위함임.
  # refs: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
  name: {{ include "scc-server.fullname" . }}-deploy-secret-job-{{ include "scc-server.secretHash" . | trunc 5 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "20"
spec:
  template:
    spec:
      serviceAccountName: {{ include "scc-server.serviceAccountName" . }}-deploy-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "mozilla/sops:v3-alpine"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              wget "https://dl.k8s.io/release/$(wget https://dl.k8s.io/release/stable.txt -O-)/bin/linux/amd64/kubectl" &&
              chmod u+x kubectl &&
              wget https://raw.githubusercontent.com/Stair-Crusher-Club/scc-server/main/infra/helm/scc-server/files/dev/secret.yaml -O secret-raw.yaml &&
              mkdir secret &&
              sops -d secret-raw.yaml > secret/secret.yaml &&
              ./kubectl create secret generic {{ include "scc-server.fullname" . }} --from-file=secret --dry-run=client -o yaml | ./kubectl apply -f -
#              TODO: kubectl을 이미지에 미리 깔아놓기
          env:
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional
            - name: AWS_REGION
              value: ap-northeast-2
            - name: AWS_ROLE_ARN
              value: "{{ .Values.deploySecret.awsRoleArn }}"
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
          volumeMounts:
            - name: aws-iam-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 86400
                  path: token
      restartPolicy: Never
  backoffLimit: 3
