apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "scc-server.fullname" . }}
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "scc-server.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "scc-server.fullname" . }}
    creationPolicy: Owner
    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        # multiline string
        secret.yaml: |
          spring:
            datasource:
              password: {{`"{{ .dbPassword }}"`}}
          scc:
            kakao:
              apiKey: {{`"{{ .apiKey }}"`}}
            admin:
              password: {{`"{{ .adminPassword }}"`}}
  data:
    - secretKey: dbPassword
      remoteRef:
        key: scc
        property: {{ .Values.env }}/db/password
    - secretKey: apiKey
      remoteRef:
        key: scc
        property: {{ .Values.env }}/kakao/apiKey
    - secretKey: adminPassword
      remoteRef:
        key: scc
        property: {{ .Values.env }}/admin/password
