apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "scc-server.fullname" . }}
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "scc-server.fullname" . }}
