apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "scc-server.fullname" . }}
  labels:
    {{- include "scc-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scc-server.name" . }}
  endpoints:
    - port: metrics
