apiVersion: v1
kind: Service
metadata:
  name: scc-admin-frontend
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: scc-admin-frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
