apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.serviceAccountName" . }}-deploy-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["create", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secrets-to-{{ include "monitoring.serviceAccountName" . }}-deploy-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
subjects:
  - kind: ServiceAccount
    name: {{ include "monitoring.serviceAccountName" . }}-deploy-secret
roleRef:
  kind: Role
  name: create-secrets
  apiGroup: rbac.authorization.k8s.io
