apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "amazon-eks-pod-identity-webhook.fullname" . }}
  namespace: {{ include "amazon-eks-pod-identity-webhook.namespace" . }}
spec:
  secretName: "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}-cert"
  commonName: "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}.{{ include "amazon-eks-pod-identity-webhook.namespace" . }}.svc"
  dnsNames:
    - "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}"
    - "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}.{{ include "amazon-eks-pod-identity-webhook.namespace" . }}"
    - "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}.{{ include "amazon-eks-pod-identity-webhook.namespace" . }}.svc"
    - "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}.{{ include "amazon-eks-pod-identity-webhook.namespace" . }}.svc.local"
  duration: "{{ .Values.pki.certManager.certificate.duration }}"
  renewBefore: "{{ .Values.pki.certManager.certificate.renewBefore }}"
  issuerRef:
    name: {{ include "amazon-eks-pod-identity-webhook.fullname" . }}
    kind: Issuer
