apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "amazon-eks-pod-identity-webhook.fullname" . }}
  namespace: {{ include "amazon-eks-pod-identity-webhook.namespace" . }}
  labels:
    {{- include "amazon-eks-pod-identity-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amazon-eks-pod-identity-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "amazon-eks-pod-identity-webhook.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /webhook
            - --annotation-prefix={{ .Values.config.annotationPrefix }}
            - --aws-default-region={{ .Values.config.defaultAwsRegion }}
            - --in-cluster=false
            - --logtostderr
            - --namespace={{ include "amazon-eks-pod-identity-webhook.namespace" . }}
            - --metrics-port={{ .Values.config.ports.metrics }}
            - --port={{ .Values.config.ports.webhook }}
            - --sts-regional-endpoint={{ .Values.config.stsRegionalEndpoint }}
            - --token-audience={{ .Values.config.tokenAudience }}
            - --token-expiration={{ .Values.config.tokenExpiration }}
            - --token-mount-path={{ .Values.config.tokenMountPath }}
            - --tls-cert=/etc/webhook/certs/tls.crt
            - --tls-key=/etc/webhook/certs/tls.key
            {{- if .Values.config.extraArgs }}
            {{- toYaml .Values.config.extraArgs | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: cert
              mountPath: "/etc/webhook/certs"
              readOnly: true
          ports:
            - name: https
              containerPort: {{ .Values.config.ports.webhook }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.config.ports.metrics }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccountName: {{ include "amazon-eks-pod-identity-webhook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cert
          secret:
            secretName: "{{ include "amazon-eks-pod-identity-webhook.fullname" . }}-cert"
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .Values.nodeSelector) . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- tpl (toYaml .Values.affinity ) . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- tpl (toYaml .Values.tolerations) . | nindent 8 }}
      {{- end }}
