apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "amazon-eks-pod-identity-webhook.serviceAccountName" . }}
  labels:
    {{- include "amazon-eks-pod-identity-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | tpl . | nindent 4 }}
  {{- end }}
