k3s:
    token: ENC[AES256_GCM,data:mfv0bzc22LMQY+QwqhfzgsVAkualJqXvdTfxhyDPguA=,iv:qq+HqLsl76PtW/fmagGlV78Sfg113ZIEZSNNBnUfH+A=,tag:MoatVAJnvSS1Wu2gl5zIrA==,type:str]
db:
    password: ENC[AES256_GCM,data:WxYZW1emmoCjlTIkBfixLQ2FufwqNckoalqj8ICm9zvHOfyQm3JYJA==,iv:d8/Jo/NG6/LmZdaZPMQ3lDsbfHoxcLGdoKOtWLU8Whc=,tag:4NUVFgCJyIjWve7ayIYcwA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:833004893731:alias/sops
          created_at: "2022-10-21T17:12:31Z"
          enc: AQICAHj7gmpDUHbiugk8njCuq/LhoXhddxY3AclpiLREvOHpwgHMbtNDU11BXucH/oAaeE/kAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6Oc6ukpRCHQjnr+9AgEQgDttjvGJ8BiB2B3gT/yQ/8dhDCcRZkbtyXUUQIUKpyefjaGzS8RnSqmJ6OgI1lB8mHk4FPf2Rn+GdTyTcA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-21T17:12:31Z"
    mac: ENC[AES256_GCM,data:o1TMea7tNc8yeV37KFG3cTPflZut8q/nB6NkJb5TmzlVa5anA/WoIa1RMN1fCgkJv8RuUZab8tCPsh41D8GlgTyb5y5AwZTrOg9gufL3wU6oN3NWrhMn7Ij31wVQ5Bb7ChwItShSBcMsV86QFYQ8YlsF3p6P0v+rCQR3mFczrQw=,iv:JThjqxoQFPDt+cv0lhYh4qw3NOaP78iaf113W8vPGvo=,tag:+gFXi92cqpQ6B1jRWUaILw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
