complexity:
  ComplexCondition:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  LongMethod:
    active: false
style:
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: false
  UnusedImports:
    active: true
  MagicNumber:
    active: false
  ReturnCount:
    active: false
naming:
  PackageNaming:
    active: false
  InvalidPackageDeclaration:
    active: false
  ConstructorParameterNaming:
    active: false
performance:
  SpreadOperator:
    active: false
exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
