services:
  postgres:
    platform: linux/arm64
    image: ghcr.io/baosystems/postgis:15-3.5
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: scc_test
  postgres-local:
    platform: linux/arm64
    image: ghcr.io/baosystems/postgis:15-3.5
    restart: always
    ports:
      - "15433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: scc
