services:
  postgres:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: scc_test
  postgres-local:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    ports:
      - "15433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: scc
