spring:
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:15432/scc
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1000
      data-source-properties.cachePrepStmts: true
      data-source-properties.prepStmtCacheSize: 250
      data-source-properties.prepStmtCacheSqlLimit: 2048
      pool-name: writer
      maximum-pool-size: 16

# actuator settings
management:
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
        add-additional-paths: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    web:
      server:
        auto-time-requests: true
        max-uri-tags: 1024
  server:
    port: 18080

scc:
  kakao:
    api-key: test

  s3:
    imageUpload:
      bucketName: test

  admin:
    password: test
