ALTER TABLE club_quest
    ADD COLUMN purpose_type VARCHAR(32) NOT NULL DEFAULT 'CRUSHER_CLUB',
    ADD COLUMN start_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN end_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;