apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scc-redash.fullname" . }}-postgresql
  labels:
    {{- include "scc-redash.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
data:
  secret-raw.yaml: |-
{{ printf "%s/secret-postgresql.yaml" .Values.filesDir | .Files.Get | indent 4 }}
