server:
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true

spring:
  datasource:
    username: scc
    url: jdbc:postgresql://ls-bc95e3df47f37bbac5e8b2cc124446d197fe4c4b.cojudf9vatyk.ap-northeast-2.rds.amazonaws.com:5432/scc_dev
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1000
      data-source-properties.cachePrepStmts: true
      data-source-properties.prepStmtCacheSize: 250
      data-source-properties.prepStmtCacheSqlLimit: 2048
      pool-name: writer
      maximum-pool-size: 16

# logging:
#   config: /app/conf/logback.xml

# actuator settings
management:
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
        add-additional-paths: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    web:
      server:
        auto-time-requests: true
        max-uri-tags: 1024

sentry:
  logging:
    enabled: true
  environment: dev

scc:
  s3:
    imageUpload:
      bucketname: scc-dev-accessibility-images
