spring:
    datasource:
        password: ENC[AES256_GCM,data:NNN5MqgpRC+nAjC1owAGYWWk/xDnfoAl0kFDKiXurPpFCBZWA7b19Q==,iv:+JsvCMOwmCFFI9A+dhzGnu+jsFruh5srNlPJg3JFFwg=,tag:bAdXNVP9pM+lrOgXGlh4VQ==,type:str]
sentry:
    dsn: ENC[AES256_GCM,data:h1TN0MLo8tr4VbE8V/S7zRbEQzmQyXAoILy4uVvF4iWgxBDn/fyCCh3PA2iEbZcOQK74CwC77jgtAmsvdG9NJWam+pKthCUt8w==,iv:AhdPfkR7wqU5EGM9q86gz4fqR4A0bpWDhP9cBO2fJmQ=,tag:TfbGTY32/R929tFITMBNjg==,type:str]
scc:
    kakao:
        apiKey: ENC[AES256_GCM,data:m17XziSoz3chj2UQQd98S+nl8ANMPxYiv85EUTgaZl8=,iv:uUr2AcgKPaF6ncd439ul7QN+0TkVhM3Hc24R/DEYTAI=,tag:03KUFBicDNOOY38VhBr5Yg==,type:str]
    admin:
        password: ENC[AES256_GCM,data:Ul+grjrA5Ugcyw==,iv:3w6IHKxsMGl+suo9OaUaPdHZ/dHERFkVqWhPSbh32Pw=,tag:WwGn3njZf0metPqM0cz7rA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:833004893731:key/9acac3b1-dedd-42f4-82e4-148832bc5d38
          created_at: "2022-11-13T08:45:46Z"
          enc: AQICAHj7gmpDUHbiugk8njCuq/LhoXhddxY3AclpiLREvOHpwgFxLdzRM/D0yxmpJ7sSJyqwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsO6vf9RYQmjmWYCUAgEQgDvk4ykiq7hnkWDkXlkeYy4SIdDxKnCq+inkgZLmPq94yw4852bD2eIKLEbl9MV4Ncx1xxMFHlNXI9RymQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-16T16:27:49Z"
    mac: ENC[AES256_GCM,data:X7EDQF0px0zVJKU0H1x5EmDkPyN2Qgxh12xnA2JFjSkYWeWntqiuNtfWtyY8QCSLrgqD1uf0yHjyEEfVEz5M0BSQIFxoXCrH62+ycESZDQYskF/s0vAQyxoYKkA+y4tPXh5j9Ln3NeBC3lxCHgutOQT2lwuI1FsG6lk9Fi5KuWs=,iv:54fJLUENG13Fg7a05fCtp6z9/T7Bim4sQBs8ZTOSFFc=,tag:G84MYBmcU4sbQOcwrvdbBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
