spring:
    datasource:
        password: ENC[AES256_GCM,data:Rn5JOzk9dk8ANzASDckiyCQNHg1t7MoHrOHRN8JZb5yQjLaAbvkYYw==,iv:kqWj69Om8uDtU8Rwa3KFLNmj0s/zPYi3Ig02ycqZ+vo=,tag:1DZFjazeOgvP49pvP/JB5w==,type:str]
sentry:
    dsn: ENC[AES256_GCM,data:9RCPhXssowRJ274cxlC3DWOOyaOCtNcOdWWP0WFPpDsbGb520zlSgxAdVNlzCPss0PrGaOZzXQuxkeVLBWSFvGjsfzJXabSeVy2JMc5uVmf+piVl97tH1zDlJos=,iv:gb3sI4GM+SIWBA7u3WyeZ+VXI6WUTduXmW3TE42ckiE=,tag:6lh2lCjxiR4pZrxCRQRIMQ==,type:str]
scc:
    kakao:
        apiKey: ENC[AES256_GCM,data:3XULZW2dZmDj4ioPhjB22wVX9QyQb5ChtHuE4NowhGw=,iv:lB/3YKD7drfR20Hqpma+SLHZ21nl7dkX+wkfFfFAduA=,tag:6jpZL/Dm+/dwHHNAzeRvTw==,type:str]
    kakao-login:
        oauth-client-id: ENC[AES256_GCM,data:JyQdF6YwxjssGLE+xFIXTBJRT8UrcneMz0uwzVUurjQ=,iv:CuzFVR28UBQzl1yEq23EnMt9tMHSPTvM8ini8P3gMmg=,tag:fTCAxQulDFSk7zwi/tuRIA==,type:str]
    admin:
        password: ENC[AES256_GCM,data:VyZvo4HRjZw6kQ==,iv:HqFCq6cMeWAb7dBxu9jNgIBOnd/+zWhNpSjCx//g2uk=,tag:cJ203Se2Er4i689pr/Eskw==,type:str]
    apple-login:
        service-id: ENC[AES256_GCM,data:qcEl8fod/ujZNOHgeBAa113rCwh1qK/6vw==,iv:m5MeqNtbCAWHETCTVf+awfHHzzxBAyTPbEsVyqTXOns=,tag:PQSORVWsBCYtCylmWqAX6A==,type:str]
        client-secret: ENC[AES256_GCM,data:2/cMTQMtgqa+ytIXZR++Zs/OJzEOk15PToyAWMihYlvBLEIMA9jZmcwTUhRLS9GCwXsuNKnRhnZ612SXBsS8HWS4kGUh9wu0FsMiQeRe/H6tWg/Uy7VzYiWFh4noTYHLra4uVjQbTjBRDbJHzwUtoXRvIlDQbbHcKdIMunSz+J2G+1MIBN+I4IreZFZYF9GJKVdTz5PruI9K6rnJ4G8Em233jzbe3zUKuk8rrnaPfKLF21Mqe3DVpbT6Jq3Dn4ajSL10OPzLIKgyfwASkTiKD3iaWUprPXep+Gu/tSlX02O5em/9ldeMJwqyzrIgreNWEr6DQtXmudIZgBsHSdwa7vriCFSu2uJPO6HfnZiEwvJwCXXgKh+Vz5InpUK2ctLAAgULMfZOKMO14IlcyD2Q74XYrfMQQSMDVA==,iv:YKzw4B0MvE3/2rX30yi+WLmwDiCw5If2HLICoDv4UC8=,tag:pT3G3yXOTu43jQWywAZRFQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-2:291889421067:alias/sops
          created_at: "2023-07-31T15:47:28Z"
          enc: AQICAHgF8bYnZL94LzSwlUWA75seDxMTpMHltwauy+q73c/QBwHRIoyFEIXTF1FnukUNtS5OAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyqhTN3Y8HIjFfHCSAgEQgDsn+IOjRX0ATvZqVcgqvkCwz94/qRi5xeBzFJDw9fViXJth/1pqfSDGHwPbMHnvYThETxR1f1pP5opIeg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-01T05:16:35Z"
    mac: ENC[AES256_GCM,data:49ka8XdodWbmotb/Fp5wq87UMkgrMSlN3OV/vxZgHTKDrBZB5JPDGrnSkFihYDRDrOw5VSV57sayuMn4r2McPQsB0L7GY3ANP9GwhPy9xCqc/tp7o8ermSD4eRKx0cCImL/n3gP/qtlBlVbdYSW2yuaUQ4HuRd3Zk1UfEvgXBRE=,iv:VkkWjFmOxyeYPHOQ6MaVQQ92/N8JRUklahCAPDs5u2g=,tag:wHZfW064r9EZ1n4X/g0adQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
