nameOverride: ''

namespaceOverride: ''

fullnameOverride: ''

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: amazon/amazon-eks-pod-identity-webhook
  tag: 'v0.4.0'

imagePullSecrets: []

config:
  annotationPrefix: eks.amazonaws.com
  defaultAwsRegion: ap-northeast-2
  extraArgs: []
  ports:
    metrics: 9999
    webhook: 8443
  stsRegionalEndpoint: true
  tokenAudience: sts.amazonaws.com
  tokenExpiration: 86400
  tokenMountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount

mutatingWebhook:
  annotations: {}
  failurePolicy: Ignore
  namespaceSelector: {}

pki:
  certManager:
    certificate:
      duration: 2160h
      renewBefore: 360h

metrics:
  podMonitor:
    enabled: false

readinessProbe:
  httpGet:
    path: /healthz
    port: metrics

livenessProbe:
  httpGet:
    path: /healthz
    port: metrics

annotations: {}

hostNetwork: false

resources:
  requests:
     cpu: 10m
     memory: 64Mi
  limits:
     memory: 64Mi

securityContext:
  readOnlyRootFilesystem: true
  runAsGroup: 1
  runAsNonRoot: false
  runAsUser: 65534

service:
  type: ClusterIP
  annotations: {}

serviceAccount:
  annotations: {}

podLabels: {}

podAnnotations: {}

podSecurityContext: {}

affinity: {}

nodeSelector: {}

tolerations: []
