spring:
  profiles:
    active: local

  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:15433/scc
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 25000
      data-source-properties.cachePrepStmts: true
      data-source-properties.prepStmtCacheSize: 250
      data-source-properties.prepStmtCacheSqlLimit: 2048
      pool-name: writer
      maximum-pool-size: 32
      minimum-idle: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

# actuator settings
management:
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
        add-additional-paths: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info,health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true # for latency percentile observability
    web:
      server:
        auto-time-requests: true
        max-uri-tags: 1024
  server:
    port: 18080


scc:
  environment: local

  jwt:
    secret: test
    old-secret: test

  kakao:
    rest-api-key: test
    admin-key: test

  kakao-login:
    oauth-client-id: test

  naver:
    open-api:
      client-id: test
      client-secret: test

  apple-login:
    service-id: test
    client-secret: test

  s3:
    imageUpload:
      bucketName: test
      thumbnailBucketName: test
      bannerBucketName: test
      crusherLabelBucketName: test

  rekognition:

  cloudfront:
    domain: test

  admin:
    password: test

  stibee:
    apiKey: test
    listId: test

  nhn-cloud:
    url-shortening:
      app-key: test

  slack:
    token: test
    channel:
      alert: "#scc-server-alert"
      reportAccessibility: "#scc-accessibility-report-test"

  open-data:
    api-key: test

  notification:
    push:
      credential: test

  sqs:
    commonQueueName: test
