name: dev-ci-cd
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:14.5-alpine
        ports:
          - 15432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: scc_test

    defaults:
      run:
        working-directory: app-server

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Check
        run: ./gradlew check

      - uses: actions/upload-artifact@v3
        name: Upload Check Report If Failed
        if: failure()
        with:
          name: test report
          path: "**/build/reports"
          retention-days: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::833004893731:role/github-action-ci-cd
          aws-region: ap-northeast-2

      - name: Build and Push Docker Image
        run: ./gradlew jib -Pversion=latest-rc

      - name: Notify CI failure to slack
        if: failure()
        run: |
          CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"[DEV] Backend CI failed. (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }} -v

  frontend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app-admin-frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Run openapi-generator
        run: |
          mkdir -p ~/bin/openapitools
          curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > ~/bin/openapitools/openapi-generator-cli
          chmod u+x ~/bin/openapitools/openapi-generator-cli
          export PATH=$PATH:~/bin/openapitools/

          mv ~/bin/openapitools/openapi-generator-cli ~/bin/openapitools/openapi-generator

          ./generate-api-spec.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::833004893731:role/github-action-ci-cd
          aws-region: ap-northeast-2

      - name: Build and Push Image
        run: ./docker-push.sh dev

      - name: Notify CI failure to slack
        if: failure()
        run: |
          CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"[DEV] Frontend CI failed. (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }} -v

  cd:
    runs-on: ubuntu-latest
    needs:
      - backend-ci
      - frontend-ci

    steps:
      - uses: actions/checkout@v3

      - name: Install kubeconfig
        env:
          SCC_K3S_KUBECONFIG: ${{ secrets.SCC_K3S_KUBECONFIG }}
        run: |
          mkdir -p ~/.kube && echo "$SCC_K3S_KUBECONFIG" > ~/.kube/config

      - uses: azure/setup-helm@v1
        with:
          version: '3.8.2'
        id: install-helm

      - uses: azure/setup-kubectl@v3
        with:
           version: 'v1.24.1'
        id: install-kubectl

      - name: Upgrade scc-server helm chart
        working-directory: infra/helm/scc-server
        run: |
          helm upgrade --install --namespace dev -f values-dev.yaml scc-server ./

      - name: Restart deploy/scc-server # tag를 latest-rc로 고정해서 사용하기 때문에 helm upgrade --install만 해서는 새 버전의 이미지가 배포되지 않는다. 따라서 강제로 rollout을 해준다.
        run: |
          kubectl rollout restart deploy/scc-server -n dev

      - name: Upgrade scc-admin-frontend helm chart
        working-directory: infra/helm/scc-admin-frontend
        run: |
          helm upgrade --install --namespace dev -f values-dev.yaml scc-admin-frontend ./

      - name: Restart deploy/scc-admin-frontend # tag를 latest-rc로 고정해서 사용하기 때문에 helm upgrade --install만 해서는 새 버전의 이미지가 배포되지 않는다. 따라서 강제로 rollout을 해준다.
        run: |
          kubectl rollout restart deploy/scc-admin-frontend -n dev

      - name: Notify CD failure to slack
        if: failure()
        run: |
          CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"[DEV] scc-server deployment failed. (<$CURRENT_GITHUB_ACTION_RUN_URL|github action run url>)\"}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }} -v

      - name: Notify CD success to slack
        if: success()
        run: |
          CURRENT_GITHUB_ACTION_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"[DEV] scc-server with latest version is deployed!\"}" ${{ secrets.SLACK_URL_SCC_SERVER_CHANNEL }} -v
