name: dev-ci-cd
on:
  push:
    branches:
      - main
      - dev-ci-cd
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:14.5-alpine
        ports:
          - 15432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: scc_test

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 19
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
